title: "FundaMendez"
description: "Sitio de la materia 'Fundamentos de programación' cátedra Méndez."
url: "https://fundamendez.github.io"

remote_theme: just-the-docs/just-the-docs

nav_enabled: true
search_enabled: true

plugins:
  - jekyll-remote-theme

search_enabled: true
enable_theme_switcher: true
favicon_ico: "/assets/img/favicon.ico"

just_the_docs:
  custom_css:
    - assets/css/custom.css
