# Definición del título, descripción y URL del sitio.
title: "FundaMendez"
description: "Sitio de la materia 'Fundamentos de programación' cátedra Méndez."
url: "https://fundamendez.github.io"

# Tema de GitHub Pages (gem-based)
theme: jekyll-theme-cayman

# Configuración de la barra de navegación.
show_downloads: false
github:
  is_project_page: false

# Links externos.
nav_external_links:
  - title: "AlgoTron"
    url: "https://algotron.com.ar/"
    opens_in_new_tab: true
  - title: "RPL"
    url: "http://www.myrpl.ar/"
    opens_in_new_tab: true
  - title: "Slack"
    url: "https://fundamendez.slack.com/"
    opens_in_new_tab: true
  - title: "Buzón de quejas"
    url: "https://docs.google.com/forms/d/e/1FAIpQLScNk-4PjhDOEC5KKiIpYg-FVf78DLZFY3hBWwn6l9Y3mi6kSQ/viewform?usp=header"
    opens_in_new_tab: true

# Links internos (barra superior)
nav_internal_links:
  - title: "Home"
    url: "/"
  - title: "Info"
    url: "/info"
  - title: "Material"
    url: "/material"
  - title: "Cronograma"
    url: "/cronograma"
  - title: "Docentes"
    url: "/docentes"
